FROM java:8-jre
WORKDIR /usr/lib
ADD ./target/orchestrationservice-0.0.1-SNAPSHOT.jar /usr/lib/orchestrationservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","orchestrationservice-0.0.1-SNAPSHOT.jar"]

